### ISSUE TITLE
Non-english usernames not valid.

### ISSUE THREAD

**Issue by patelnilay** [goksan/Denouement#6]
# Expected Behavior

Username should be able to be created with any language.

# Current Behavior
I get a django error page in response.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. Go to the sign up page
2. Input username as anything other the english alphabet. 
3. Get Django Error.

![image](https://user-images.githubusercontent.com/31472449/50003425-7a335b80-ff9b-11e8-81b3-f701328e3c0b.png)

![image](https://user-images.githubusercontent.com/31472449/50003384-5b34c980-ff9b-11e8-96aa-58e415ce47ec.png)

**Comment by goksan** [comment]
This was mistaken for another issue
